services:
  database:
    container_name: nepalinno
    image: postgres:latest
    environment:
      POSTGRES_DB: nepalinno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"


    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nepalinno_app
volumes:
  db_data:

networks:
  nepalinno_app:
