basePath: /api/v1
definitions:
  router.Item:
    properties:
      id:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: this is the documentation for the Budd API service. Budd is a Nepal-based
    tech blogging platform.
  title: Budd API Documentation
  version: "1.0"
paths:
  /items:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/router.Item'
            type: array
      summary: Get all items
      tags:
      - items
    post:
      parameters:
      - description: Item to create
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/router.Item'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/router.Item'
      summary: Create a new item
      tags:
      - items
  /items/{id}:
    delete:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete an item
      tags:
      - items
    get:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.Item'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get an item by ID
      tags:
      - items
    put:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/router.Item'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.Item'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Update an existing item
      tags:
      - items
swagger: "2.0"
