basePath: /api/v1
definitions:
  entity.Blog:
    properties:
      author:
        $ref: '#/definitions/entity.User'
      author_id:
        type: string
      content:
        type: string
      created_at:
        description: Timestamps
        type: string
      deleted_at:
        type: string
      id:
        type: string
      is_published:
        type: boolean
      thumbnail_image:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  entity.User:
    properties:
      auth_provider:
        type: string
      blogs:
        description: relationships
        items:
          $ref: '#/definitions/entity.Blog'
        type: array
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      image:
        type: string
      is_active:
        type: boolean
      is_verified:
        type: boolean
      last_login:
        type: string
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
  router.BlogInput:
    properties:
      content:
        type: string
      tags:
        description: Tag names or IDs
        items:
          type: string
        type: array
      thumbnail_image:
        description: Thumbnail URL
        type: string
      title:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: this is the documentation for the Budd API service. Budd is a Nepal-based
    tech blogging platform.
  title: Budd API Documentation
  version: "1.0"
paths:
  /auth/google_user_create:
    post:
      consumes:
      - application/json
      description: Create a new user using Google OAuth credentials or return an existing
        user.
      parameters:
      - description: Google OAuth Token
        in: body
        name: credential
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Google User Creation
      tags:
      - User
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout the user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout
      tags:
      - User
  /auth/me:
    get:
      consumes:
      - application/json
      description: Get the user details if authenticated
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get if the user is authenticated
      tags:
      - User
  /blog:
    post:
      consumes:
      - application/json
      description: Create a new blog post.
      parameters:
      - description: Blog post details
        in: body
        name: blog
        required: true
        schema:
          $ref: '#/definitions/router.BlogInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Blog'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Blog Post
      tags:
      - Blog
  /blog/save:
    post:
      consumes:
      - application/json
      description: Save a new blog post.
      parameters:
      - description: Blog post details
        in: body
        name: blog
        required: true
        schema:
          $ref: '#/definitions/router.BlogInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Blog'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Save Blog Post
      tags:
      - Blog
swagger: "2.0"
